name: "Jira Action Man"
description: "Extract Jira issue keys from GitHub events (branches, PR titles, commits, PR body)"
author: "nick"

inputs:
  projects:
    description: 'Comma-separated Jira project prefixes to match (e.g. "PROJ,TEAM"). Empty = match all.'
    required: false
    default: ""
  from:
    description: "Comma-separated sources to check: branch, title, commits, body"
    required: false
    default: "branch,title,commits"
  fail_on_missing:
    description: "Fail the action if no Jira keys are found"
    required: false
    default: "false"
  blocklist:
    description: 'Comma-separated prefixes to ignore (e.g. "SHA,UTF"). Overrides the default blocklist. Set to "none" to disable.'
    required: false
    default: ""
  issue_pattern:
    description: "Custom regex pattern for matching issue keys. Overrides the default pattern."
    required: false
    default: ""
  post_to_jira:
    description: "Post PR description as a comment on linked Jira tickets"
    required: false
    default: "false"
  jira_base_url:
    description: "Jira instance base URL (e.g. https://yourorg.atlassian.net)"
    required: false
    default: ""
  jira_email:
    description: "Jira account email for API authentication"
    required: false
    default: ""
  jira_api_token:
    description: "Jira API token for authentication"
    required: false
    default: ""
  jira_comment_mode:
    description: 'Comment behavior: "update" (default) updates existing comment, "new" always creates a new comment, "minimal" posts a single-line link'
    required: false
    default: "update"
  jira_fail_on_error:
    description: "Fail the action if posting to Jira fails (default: warn only)"
    required: false
    default: "false"
  github_token:
    description: "GitHub token for downloading GitHub-hosted images in PR bodies and authenticating API requests. Usually secrets.GITHUB_TOKEN."
    required: false
    default: ""
  allowed_image_hosts:
    description: 'Comma-separated hostnames allowed for image downloads (e.g. "user-images.githubusercontent.com,example.com"). When set, only these hosts are permitted. When empty, all non-private HTTPS hosts are allowed.'
    required: false
    default: ""

outputs:
  keys:
    description: "JSON array of unique sorted Jira issue keys"
  key:
    description: "First Jira issue key found (convenience)"
  found:
    description: '"true" if any keys were found, "false" otherwise'

runs:
  using: "node20"
  main: "dist/index.js"
